name: Production CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy changes to the production release channel
    runs-on: ubuntu-latest
    env:
      EXPO_RELEASE_CHANNEL: prod
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Download Expo CLI
        run: |
          npm install expo-cli --global
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Deploy
        run: expo publish --release-channel ${EXPO_RELEASE_CHANNEL}
